### ISSUE TITLE
Blog tags / categories

### ISSUE THREAD

**Issue by smlewi** [gopperman/fader-theme#19]
Is he going to have more? If so I am wondering if we can decrease the width and increase the width of the content on the left slightly....right now the categories just seem to be dominating. We can chat about this on gchat.

**Comment by gopperman** [comment]
Would this be good?

![image](https://cloud.githubusercontent.com/assets/1591557/14592362/aeee85d2-04eb-11e6-99fd-0891d0492c2f.png)

**Comment by gopperman** [comment]
Leaving as-is
