### ISSUE TITLE
Google Analytics?

### ISSUE THREAD

**Issue by gopperman** [gopperman/fader-theme#27]

**Comment by gopperman** [comment]
@alecopperman, can you make me an admin in GA?

**Comment by alecopperman** [comment]
done

On Sun, Apr 24, 2016 at 7:25 PM, Greg Opperman notifications@github.com
wrote:

> @alecopperman https://github.com/alecopperman, can you make me an admin
> in GA?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/gopperman/fader-theme/issues/27#issuecomment-214065165

## 

Alec Opperman
Outreach Coordinator
Union Square Practice http://unionsquarepractice.com
