### ISSUE TITLE
Embed styles

### ISSUE THREAD

**Issue by alecopperman** [gopperman/fader-theme#32]
http://fader.gopperman.com/category/media/

**Comment by gopperman** [comment]
@alecopperman, to embed things responsively, here's what you need to do:
- For youtube, vimeo, etc, just copy and paste the link (ex https://www.youtube.com/watch?v=8aYxuwsAMGc ) on its own line in a post. DO NOT copy the embed code provided by youtube.
- For video embeds not supported by wordpress, just copy and paste the embed code in your text tab, but wrap the code in `<div class="embed__container">...</div>`. For example:

`<div class="embed__container"><script src="http://video.foxbusiness.com/v/embed.js?id=4840581830001&amp;w=466&amp;h=263" type="text/javascript"></script><noscript>Watch the latest video at <a href="http://video.foxbusiness.com">video.foxbusiness.com</a></noscript></div>`
