### ISSUE TITLE
Book Seller Icons on Book Page

### ISSUE THREAD

**Issue by alecopperman** [gopperman/fader-theme#36]
Books a Million, IndieBound, Barnes and Noble, Amazon and iTunes

**Comment by gopperman** [comment]
@smlewi, can you mock this up? Thanks!

**Comment by smlewi** [comment]
[
[JF Book Sellers Logos.zip](https://github.com/gopperman/fader-theme/files/249242/JF.Book.Sellers.Logos.zip)
![jfader-ui-book-20160425](https://cloud.githubusercontent.com/assets/13255767/15022607/5826bc4e-11e1-11e6-8786-9e8a47c0901b.jpg)

](url)

**Comment by alecopperman** [comment]
Love this

On Wed, May 4, 2016 at 1:17 PM, smlewi notifications@github.com wrote:

> [
> JF Book Sellers Logos.zip
> https://github.com/gopperman/fader-theme/files/249242/JF.Book.Sellers.Logos.zip
> [image: jfader-ui-book-20160425]
> https://cloud.githubusercontent.com/assets/13255767/15022607/5826bc4e-11e1-11e6-8786-9e8a47c0901b.jpg
> 
> ](url)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gopperman/fader-theme/issues/36#issuecomment-216936812

## 

Alec Opperman
Outreach Coordinator
Union Square Practice http://unionsquarepractice.com
