### ISSUE TITLE
Feature request: Some sort of CTA at the bottom

### ISSUE THREAD

**Issue by alecopperman** [gopperman/fader-theme#42]
In earlier mockups, you had an email list signup. Happy to get input here, but maybe another way to access the contact form or something like that.

**Comment by gopperman** [comment]
Yeah, that's a good idea, I've wanted to do that.

**Comment by gopperman** [comment]
Suz, can you mock up or suggest a solution to this?

**Comment by alecopperman** [comment]
I don't see a solution on the dev site or anywhere?

On Thu, Apr 28, 2016 at 4:37 PM, smlewi notifications@github.com wrote:

> Closed #42 https://github.com/gopperman/fader-theme/issues/42.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gopperman/fader-theme/issues/42#event-644853292

## 

Alec Opperman
Outreach Coordinator
Union Square Practice http://unionsquarepractice.com

**Comment by gopperman** [comment]
Sorry Suz closed this prematurely

**Comment by smlewi** [comment]
![jfader-ui-home-20160425](https://cloud.githubusercontent.com/assets/13255767/15022642/7ad54ea4-11e1-11e6-8c14-0f576655f4c5.jpg)

**Comment by alecopperman** [comment]
Should I forward this along to JF with the other thing?

On Wed, May 4, 2016 at 1:18 PM, smlewi notifications@github.com wrote:

> [image: jfader-ui-home-20160425]
> https://cloud.githubusercontent.com/assets/13255767/15022642/7ad54ea4-11e1-11e6-8c14-0f576655f4c5.jpg
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gopperman/fader-theme/issues/42#issuecomment-216937248

## 

Alec Opperman
Outreach Coordinator
Union Square Practice http://unionsquarepractice.com

**Comment by smlewi** [comment]
Forward for approval? Yes please. What other thing?

**Comment by alecopperman** [comment]
The bookseller icons.

On Wed, May 4, 2016 at 10:46 PM, smlewi notifications@github.com wrote:

> Forward for approval? Yes please. What other thing?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gopperman/fader-theme/issues/42#issuecomment-217063252

## 

Alec Opperman
Outreach Coordinator
Union Square Practice http://unionsquarepractice.com

**Comment by smlewi** [comment]
Yes
