### ISSUE TITLE
Contact form: Add Phone #

### ISSUE THREAD

**Issue by alecopperman** [gopperman/fader-theme#43]
Jonathan wants his phone number displayed: 212-777-3601

**Comment by gopperman** [comment]
@smlewi Where can we add this?

**Comment by alecopperman** [comment]
Are we adding this to the contact form or did we put it at the bottom of the page instead?

**Comment by gopperman** [comment]
We added it to the footer instead, this can be closed.

**Comment by gopperman** [comment]
We added it to the footer instead, this can be closed.
