### ISSUE TITLE
Wish: 3d book

### ISSUE THREAD

**Issue by alecopperman** [gopperman/fader-theme#56]
3D book at the bottom of the home page and on LaS page. Examples on Sam Sommers' website. http://samsommers.com/books/

**Comment by smlewi** [comment]
Here's a mockup. What do you guys think?[
![lifeassport_book_mockup](https://cloud.githubusercontent.com/assets/13255767/15059028/dd45a61c-12d4-11e6-8a98-01d350ddfa92.png)
](url)

**Comment by smlewi** [comment]
Also, I think this book is totally fine to replace the one on the bottom of the home page and then again on the book page (up top), but I think we should pull the book in general from the home page hero image and just full on mimic Sam Sommers.

**Comment by alecopperman** [comment]
Hey Suz, the book up top is a point of contentious issue. Everyone thinks
it looks terrible except Jonathan, but he's compromised on just having it
up there or the month of May. I hope to god he doesn't want the 3d version
up top.

I think that mockup looks great. I'll send to Jonathan.

On Thu, May 5, 2016 at 6:23 PM, smlewi notifications@github.com wrote:

> Also, I think this book is totally fine to replace the one on the bottom
> of the home page and then again on the book page (up top), but I think we
> should pull the book in general from the home page hero image and just full
> on mimic Sam Sommers.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gopperman/fader-theme/issues/56#issuecomment-217297159

## 

Alec Opperman
Outreach Coordinator
Union Square Practice http://unionsquarepractice.com

**Comment by smlewi** [comment]
Totally understand :)

We'll review it after May.

**Comment by alecopperman** [comment]
Here's Jonathan's feedback:

Can we get the book rotated a little bit more so the front cover is easier
to read? So maybe a few degrees counter-clockwise (I think that's the right
direction). Also, reduce the book thickness by about 10% but rotating might
help it look just a tad skinnier.

On Fri, May 6, 2016 at 10:45 AM, smlewi notifications@github.com wrote:

> Totally understand :)
> 
> We'll review it after May.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gopperman/fader-theme/issues/56#issuecomment-217460078

## 

Alec Opperman
Outreach Coordinator
Union Square Practice http://unionsquarepractice.com

**Comment by smlewi** [comment]
So this is a psd template I downloaded. I can't actually create a 3D mockup myself so rotating / skewing doesn't work that well for as quick tweak. I chose this template since it looks exactly like Somers...do you think you want a straight on book instead? In looking at 3D book templates all seem to be on an angle or straight on.

**Comment by smlewi** [comment]
Tried making it skinnier - that makes it look more skewed to the left :(

**Comment by smlewi** [comment]
Omg omg found another free one that is on less of an skew. Does this work?
![lifeassport_book_mockup-2](https://cloud.githubusercontent.com/assets/13255767/15086477/f58c5eca-1395-11e6-90ee-f3f2d297a049.png)

**Comment by alecopperman** [comment]
JF and I love it.

Go ahead and implement. He also wants this next to his face - but that
would be too much right?

On Fri, May 6, 2016 at 5:22 PM, smlewi notifications@github.com wrote:

> Omg omg found another free one that is on less of an skew. Does this work?
> [image: lifeassport_book_mockup-2]
> https://cloud.githubusercontent.com/assets/13255767/15086477/f58c5eca-1395-11e6-90ee-f3f2d297a049.png
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gopperman/fader-theme/issues/56#issuecomment-217561761

## 

Alec Opperman
Outreach Coordinator
Union Square Practice http://unionsquarepractice.com

**Comment by smlewi** [comment]
Well I think it would be misrepresentation since his face is not on the book, right?

**Comment by alecopperman** [comment]
Oh, sorry, I meant using the 3d book in the hero, sort of like it is now.

On Mon, May 9, 2016 at 11:00 AM, smlewi notifications@github.com wrote:

> Well I think it would be misrepresentation since his face is not on the
> book, right?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gopperman/fader-theme/issues/56#issuecomment-217889879

## 

Alec Opperman
Outreach Coordinator
Union Square Practice http://unionsquarepractice.com

**Comment by smlewi** [comment]
I'll see if I can mock something up that looks ok. Added to the list!

**Comment by smlewi** [comment]
Here's a mockup. I don't love it but I do think we should be consistent on which style of book design we use throughout the site. Otherwise things start to look messy. What do you think?
![jfader-newfeature-20160509](https://cloud.githubusercontent.com/assets/13255767/15133731/9130bb56-161a-11e6-81bd-852bc3bab5ed.jpg)

**Comment by alecopperman** [comment]
Go ahead and implement, sorry for the delay.

**Comment by smlewi** [comment]
Greg - book files are attached
![lifeassport_book_mockup-2large](https://cloud.githubusercontent.com/assets/13255767/15435103/3fa08a3e-1e6f-11e6-9366-43102fc50efa.png)
![lifeassport_book_mockup-2small_322x484](https://cloud.githubusercontent.com/assets/13255767/15435104/3fa0a7da-1e6f-11e6-9ba0-5cc718118a72.png)
